##启动端口
server:
  port: 8081

##数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xblog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

##mybatis配置
mybatis:
  typeAliasesPackage: springboot.xblogserver.domain
  mapperLocations: classpath:mapper/*.xml

##日志
logging:
  level:
    springboot.xblogserver.dao: debug
